server:
  port: 8070
spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:postgresql://localhost:5432/logic_ms
    username: logic_ms_user
    password: 1q2w3e
    driver-class-name: org.postgresql.Driver
  liquibase:
    enabled: true
    change-log: classpath:/changelog/master.xml
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  cloud:
    stream:
      function:
        definition: newUserListener
      kafka:
        binder:
          brokers: localhost
          defaultBrokerPort: 9092
          replication-factor: 1
      bindings:
        newUserListener-in-0:
          destination: additional.info.topic
          group: logic.ms.group
          consumer:
            concurrency: 10
            max-attempts: 1

application:
  errorMessages:
    internalError: internal error
    wrongRequestParameters: wrong request parameters
    integrationError: Error while integration with external service.
  externalServices:
    fileSystem:
      name: file-system-client
      url: http://localhost:8080/

  keycloakServerProfile:
    url: http://localhost:8484/auth/realms/file-system-realm/protocol/openid-connect/token
    grantType: password
    clientId: file-system-client
    username: file-system-user
    password: 1q2w3e
  internalServerProfile:
    url: http://localhost:8080/oauth/token
    grantType: client_credentials
    clientId: test-system
    clientSecret: my-client-secret
#keycloak:
#  auth-server-url: #FIXME
#  realm: #FIXME
#  resource:#FIXME
#  bearer-only: true
#  security-constraints:
#    - authRoles:
#        - uma_authorization
#      securityCollections:
#        - patterns:
#            - /cluster/*
#            - /directory/*
#            - /file/*
#            - /recreate/*