server:
  port: 8070
spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: project.notes.restore@gmail.com
    password: pzjcmjfkogznsdzo
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://${OAUTH_HOST:localhost}:${OAUTH_PORT:8081}/.well-known/jwks.json
  rabbitmq:
    host: ${RABBIT_HOST:localhost}
    username: ${RABBIT_USERNAME:guest}
    port: ${RABBIT_PORT:5672}
    virtualHost: /
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:logic_ms}
    username: ${DB_USER:logic_ms_user}
    driver-class-name: org.postgresql.Driver
  liquibase:
    enabled: true
    change-log: classpath:/changelog/master.xml
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  cloud:
    stream:
      defaultBinder: rabbit
      function:
        definition: newUserListener;fileSystemNotificationListener
      kafka:
        binder:
          brokers: ${KAFKA_HOST:localhost}
          defaultBrokerPort: ${KAFKA_PORT:29092}
          replication-factor: 1
      bindings:
        fileSystemNotificationListener-in-0:
          destination: ${RABBIT_EXCHANGE:filesystem.notifications.exchange}
          contentType: text/plain
          binder: rabbit
        newUserListener-in-0:
          binder: kafka
          destination: ${KAFKA_TOPIC:additional.info.topic}
          group: ${KAFKA_GROUP:logic.ms.group}
          consumer:
            concurrency: 10
            max-attempts: 1
      rabbit:
        bindings:
          fileSystemNotificationListener-in-0:
            consumer:
              binding-routing-key: "#"

application:
  sender: project.notes.restore@gmail.com
  topic: Information
  systemName: notes-system
  errorMessages:
    internalError: internal error
    wrongRequestParameters: wrong request parameters
    integrationError: Error while integration with external service.
    requestedResourceNotFound: Requested resource not found.
    notYourDirectory: Target directory is not yours.
    canNotDenyAccess: Can not deny access. User has no access to this note.
  externalServices:
    fileSystem:
      name: file-system-client
      url: http://${FILE_SYSTEM_HOST:localhost}:${FILE_SYSTEM_PORT:8080}/
    userData:
      name: user-data-system-client
      url: http://${USER_DATA_SYSTEM_HOST:localhost}:${USER_DATA_SYSTEM_PORT:8082}/

  messageTemplates:
    clusterWasArchived: "Здравствуйте!\nВы долго не проявляли никакой активности в системе.
    Все ваши записки были помещены в архив.\nОбратитесь к администратору для разархивирования."
    clusterWillBeDeletedSoon: "Здравствуйте!\nВы слишком долго отсутствовали в системе.\nВсе ваши записки
    временно удалены. Обратитесь к администратору для восстановления, иначе они будут удалены окончательно через {daysCount} дней!!!"
    clusterIrrevocableDeleted: "Здравствуйте!\nВас так долго не было в системе, что ваши записки были удалены."

  keycloakServerProfile:
    url: http://localhost:8484/auth/realms/file-system-realm/protocol/openid-connect/token
    grantType: password
    clientId: file-system-client
    username: file-system-user
    password: 1q2w3e
  internalServerProfile:
    url: http://localhost:8081/oauth/token
    grantType: client_credentials
    clientId: notes-system
    clientSecret: my-client-secret
#keycloak:
#  auth-server-url: #FIXME
#  realm: #FIXME
#  resource:#FIXME
#  bearer-only: true
#  security-constraints:
#    - authRoles:
#        - uma_authorization
#      securityCollections:
#        - patterns:
#            - /cluster/*
#            - /directory/*
#            - /file/*
#            - /recreate/*